language: scala
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_c8e73cee7f92_key -iv $encrypted_c8e73cee7f92_iv
  -in .travis_deploy_key.enc -out .travis_deploy_key -d
jdk: oraclejdk8
addons:
  ssh_known_hosts: botlabs.ru
scala:
- 2.12.8
branches:
  only:
  - master
  - stage
notifications:
  email:
    recipients:
    - aybek.hashimov@gmail.com
script: sbt assembly
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis_deploy_key
  - ssh-add .travis_deploy_key
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      scp target/scala-2.12/catpc-assembly-0.1.jar oybek@botlabs.ru:/home/oybek/catpc/master/catpc-new.jar;
      ssh -t oybek@botlabs.ru 'cd /home/oybek/catpc/master && mv catpc-new.jar catpc.jar && ./restart.sh';
    fi
  - if [[ $TRAVIS_BRANCH == "stage" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      scp target/scala-2.12/catpc-assembly-0.1.jar oybek@botlabs.ru:/home/oybek/catpc/stage/catpc-new.jar;
      ssh -t oybek@botlabs.ru 'cd /home/oybek/catpc/stage && mv catpc-new.jar catpc.jar && restart.sh';
    fi
