pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd etransport && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd etransport && mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'tmux new -d -s etransport "java -jar etransport/target/etransport-0.0.1-SNAPSHOT.jar -Dspring.config.location=file:///~/cfg/master.properties"'
            }
        }
    }
}

