pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd etransport && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd etransport && mvn test'
            }
        }
    }
}

